plugins {
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.gradle.userdev' version '7.1.25'
    id 'com.matthewprenger.cursegradle' version '1.4.0' apply false
    id 'com.modrinth.minotaur' version '[2,)' apply false
}

ext.config = parseConfig(file('../build.properties'))
ext.customConfig = parseConfig(file('build.properties'))
ext.config.MIN_SUPPORTED_VERSION = customConfig.MIN_SUPPORTED_VERSION
ext.config.MINECRAFT_VERSION = customConfig.MINECRAFT_VERSION
ext.config.NEOFORGE_VERSION = customConfig.NEOFORGE_VERSION
ext.config.JAVA_LANG_VERSION = customConfig.JAVA_LANG_VERSION

project.version = config.VERSION
project.group = "${config.GROUP}.${config.ARTIFACT}"
base.archivesName = "${config.ARCHIVES_BASE_NAME}-${config.MIN_SUPPORTED_VERSION}"

java {
    toolchain.languageVersion = JavaLanguageVersion.of(Integer.parseInt(config.JAVA_LANG_VERSION as String))
    withSourcesJar()
}

runs {
    configureEach {
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client { }

    server {
        programArgument '--nogui'
    }

    data {
        programArguments.addAll '--mod', 'nebs', '--all',
            '--output', file('src/generated/resources/').absolutePath,
            '--existing', file('src/main/resources/').absolutePath,
            '--existing', file('../common/src/main/resources/').absolutePath
    }
}

sourceSets.main.resources {
    srcDir 'src/main/js'
    srcDir 'src/generated/resources'
    srcDir '../common/src/main/resources'
}

dependencies {
    implementation "net.neoforged:neoforge:${config.NEOFORGE_VERSION}"
}

jar {
    manifest {
        attributes([
            'Specification-Title'   : config.TITLE,
            'Specification-Vendor'  : config.AUTHOR,
            'Specification-Version' : '1',
            'Implementation-Title'  : config.TITLE,
            'Implementation-Version': config.VERSION,
            'Implementation-Vendor' : config.AUTHOR
        ])
    }
}

afterEvaluate {
    tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
    tasks.withType(Test).configureEach { defaultCharacterEncoding = 'UTF-8' }
    tasks.withType(Javadoc).configureEach { options.encoding = 'UTF-8' }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

import groovy.json.JsonOutput
import groovy.json.JsonSlurper
processResources {
    doLast {
        fileTree(dir: outputs.files.asPath, include: ['**/*.json', '**/*.mcmeta']).each {
            try {
                it.text = JsonOutput.toJson(new JsonSlurper().parse(it))
            } catch (Exception e) {
                project.logger.error("Failed to minify file '${it.path}'.")
                throw e
            }
        }
    }
}

def parseConfig(File config) {
    config.withReader {
        def prop = new Properties()
        prop.load(it)
        return (new ConfigSlurper().parse(prop))
    }
}

idea.module { downloadJavadoc = downloadSources = true }
